[[main]]
none = "none"

[[main]]
name = "About"
pageRef = "about"
identifier = "about"
weight = 10

[[main]]
name = "Portfolio"
pageRef = "Portfolio"
identifier = "zGDozhDBLR"
weight = 20

[[main]]
name = "Blog"
pageRef = "Blog"
identifier = "JfOAp6veZf"
weight = 30

[[footer]]
none = "none"
